export const  Food=[
    {
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:true,
        sub:[{
            title:"njoke,"
        },{
            title:"riza"
        }]
    },
    {
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    },{
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    },{
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    },{
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    },{
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    },{
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    }
    
]


export const  MesniMeni=[
    {
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:true,
        sub:[{
            title:"njoke,"
        },{
            title:"riza"
        }]
    },
    {
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    },{
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    },{
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    },{
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    },{
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    },{
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    }
    
]
export const  RibljiiMeni=[
    {
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:true,
        sub:[{
            title:"njoke,"
        },{
            title:"riza"
        }]
    },
    {
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    },{
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    },{
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    },{
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    },{
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    },{
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    }
    
]
export const Deserti=[
    {
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:true,
        sub:[{
            title:"njoke,"
        },{
            title:"riza"
        }]
    },
    {
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    },{
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    },{
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    },{
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    },{
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    },{
        name:"Juha",
        subtitle:"Subtitle",
        price:6,
        has_sub:false,
        sub:[{}]
    }
    
]

export const Red=[
    {
        name:"Red",
        subtitle:"Subtitle",
        price:6,
        
    },
    {
        name:"Red",
        subtitle:"Subtitle",
        price:6,
      
    },
    {
        name:"Red",
        subtitle:"Subtitle",
        price:6,
        
    }
]

export const White=[
    {
        name:"White",
        subtitle:"Subtitle",
        price:6,
       
    },
    {
        name:"White",
        subtitle:"Subtitle",
        price:6,
        
    },
    {
        name:"White",
        subtitle:"Subtitle",
        price:6,
        
    }
]
